version: '3.8'
services:
  playwright-tests:
    build: .
    environment:
      - BASE_URL=https://the-internet.herokuapp.com
    volumes:
      - ./test.txt:/app/test.txt
    command: mvn test -Dtest=FileUploadTest