#name: Java CI
#
#on: [push]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Build Docker image
#        run: docker build -t playwright-junit-test .
#
#      - name: Run tests
#        run: |
#          docker run --rm \
#            -e BASE_URL=https://the-internet.herokuapp.com \
#            -v ${PWD}/test.txt:/app/test.txt \
#            playwright-junit-test \
#            mvn test -Dtest=FileUploadTest

name: Docker Tests

on:
  workflow_dispatch:  # Ручной запуск через UI GitHub
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'src/test/java/FileUploadTest.java'  # Запуск при изменении файлов, связанных с Docker

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t playwright-junit-test .

      # Запуск теста в контейнере
      - name: Run Docker tests
        run: |
          docker run --rm \
            -e BASE_URL=https://the-internet.herokuapp.com \
            -v ${PWD}/test.txt:/app/test.txt \
            playwright-junit-test \
            mvn test -Dtest=FileUploadTest